server:
  port: 8082
# servlet:
#    context-path: /Weather
spring:
      thymeleaf:
          cache: false
          enabled: false

      mvc:
          view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
          static-path-pattern: /**

      main:
        allow-bean-definition-overriding: true
        
#      mail:
#        host: 
#        username: XXXXXXXXX
#        password: XXXXXXXXX
#        protocol: smtp
#        default-encoding: UTF-8





     

      
      
      